name: fast_tabnet
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python
  - pip
  - fastai
  - pytorch>=1.3
  - cuda100 
  - cudatoolkit
  - bayesian-optimization
  - pip:
    - pytorch-tabnet>=1.1
    - fastai
    - nbdev
    - twine
    - wget
    - mat4py
